version: "3.9"

services:

  fuseki:
    image: secoresearch/fuseki
    restart: always
    environment:
      ADMIN_PASSWORD: password
      ENABLE_DATA_WRITE: "true"
      ENABLE_UPDATE: "true"
      ENABLE_UPLOAD: "true"
    ports:
      - "3030:3030"

  flask-api:
    image: edusalcas/sc-api:v0
    restart: always
    ports:
      - "5000:5000"

  db:
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - local_path_to_volume:/var/lib/postgresql/data